"""
AgentState — Shared state object passed between LangGraph nodes.

Phase 1: Contains all data needed to reproduce the existing stream_workflow()
Phase 2+: Will be extended with approval flags, human feedback, etc.
"""
from typing import Annotated, Any, TypedDict
import operator


class AgentState(TypedDict):
    # ── Conversation ──────────────────────────────────────────────
    messages: list[dict]              # Full programmer message history
    user_task: str                    # Latest user request (plain text)
    chat_history_display: list[dict]  # UI chat history (role/content dicts)
    # ── Planner & HITL (Phase 2) ──────────────────────────────────
    analysis_plan: str                # Step-by-step logic generated by Planner
    review_status: str                # "APPROVE" | "REJECT" | "CLARIFICATION"
    review_feedback: str              # User's raw text feedback
    review_history: list[dict]        # Audit log of all reviews and iterations

    # ── Code execution ────────────────────────────────────────────
    generated_code: str               # Python code extracted from LLM response
    critic_verdict: bool              # Quality gate for syntax/dangerous code
    exe_result: str                   # Raw stdout/stderr from sandbox
    exe_sign: str                     # "text" | "error" | ...

    # ── Retry counters ────────────────────────────────────────────
    syntax_attempts: int              # Code fix attempts (inner repair loop)
    semantic_attempts: int            # Semantic verify retries

    # ── Verifier ─────────────────────────────────────────────────
    verdict: dict                     # Latest verdict from SemanticVerifier
    inspector_hypotheses: str         # Inspector's repair suggestions


    # ── Final output ──────────────────────────────────────────────
    final_report: str                 # Markdown report shown to user
    error_message: str                # Last error (if any)
