import os
import json
import re
from typing import List, Dict, Optional

from dgm_agent_v2.interfaces.llm_client import ILLMClient
from dgm_agent_v2.core.evolution_hyperparams import HYPERPARAMS, EvolutionHyperparams
from dgm_agent_v2.evolution.evaluator import FitnessEvaluator
from dgm_agent_v2.evolution.diagnoser import Diagnoser
from dgm_agent_v2.evolution.strategy_validator import StrategyValidator

class DarwinOrchestrator:
    """
    [SOTA] The Outer Loop engine of the Darwin Godel Machine (SAEA Bridge).
    Reads candidate mutants (generated by Inner Loop) from evolution_archive.json,
    selects the best "goldilocks" candidate, and evaluates its fitness via Docker Sandbox.
    """

    def __init__(self, llm_client: ILLMClient, evaluator: FitnessEvaluator, archive_path: str = "dgm_agent_v2/archive/evolution_archive.json"):
        # [SOLID] Dependency Injection
        self.llm_client = llm_client
        self.evaluator = evaluator
        self.diagnoser = Diagnoser(llm_client)
        self.archive_path = archive_path
        self.generation = 0

    def _load_archive(self) -> List[Dict]:
        if not os.path.exists(self.archive_path):
            return []
        with open(self.archive_path, 'r', encoding='utf-8') as f:
            try:
                return json.load(f)
            except json.JSONDecodeError:
                return []

    def _save_archive(self, archive_data: List[Dict]):
        with open(self.archive_path, 'w', encoding='utf-8') as f:
            json.dump(archive_data, f, indent=4)

    def _select_best_goldilocks_candidate(self, archive_data: List[Dict]) -> Optional[Dict]:
        """
        [Cầu nối SAEA] Lọc các candidate đã vượt qua vòng Inner Loop.
        Chỉ những bản code đạt chuẩn "PASS" ở bộ lọc Epiplexity mới được gửi đi
        chạy Compiler thật, giúp tiết kiệm 95% chi phí điện toán.
        """
        valid_candidates = [
            c for c in archive_data 
            if c.get("goldilocks_status") == "PASS" and not c.get("outer_evaluated", False)
        ]
        
        if not valid_candidates:
            return None
            
        # Ưu tiên candidate có điểm Epiplexity (độ khó) cao nhất trong ngưỡng an toàn
        valid_candidates.sort(key=lambda x: x.get("epiplexity_score", 0.0), reverse=True)
        return valid_candidates[0]

    def run_outer_loop_cycle(self):
        """
        Thực thi 1 chu kỳ Tiến hóa ngoài (Outer Loop Generation).
        """
        print(f"\n[DGM OUTER LOOP] === Bắt đầu Thế hệ (Generation) {self.generation} ===")
        archive_data = self._load_archive()
        if not archive_data:
            print("[DGM OUTER LOOP] Archive trống. Đang chờ Inner Loop sinh mutant...")
            return

        # 1. Khôi phục ADN từ thế hệ xuất sắc nhất (Khắc phục Amnesia Evolution)
        best_overall = max(archive_data, key=lambda x: x.get("fitness_score", 0.0), default=None)
        if best_overall and "hyperparams" in best_overall:
            global HYPERPARAMS
            HYPERPARAMS = EvolutionHyperparams.from_dict(best_overall["hyperparams"])

        # 2. Giao thức AGP: Kích hoạt trôi dạt hệ gen (Evolutionary Drift)
        HYPERPARAMS.drift()
        self.generation += 1

        # 3. Chọn ứng viên từ Inner Loop
        candidate = self._select_best_goldilocks_candidate(archive_data)
        if not candidate:
            print("[DGM OUTER LOOP] Không có candidate mới nào đạt chuẩn Goldilocks.")
            return

        print(f"[DGM OUTER LOOP] Bắt đầu chấm điểm Candidate từ chu kỳ {candidate.get('cycle', 'unknown')} bằng Real Compiler...")

        # 4. Thực chiến tại Sandbox (Đánh giá mã đa ngôn ngữ trên Polyglot)
        # Evaluator sẽ spin-up Docker container, chạy test và trả về fitness_score
        evaluation_result = self.evaluator.evaluate(candidate.get("code", ""))

        # Ghi nhận kết quả
        candidate["outer_evaluated"] = True
        candidate["fitness_score"] = evaluation_result.get("pass_rate", 0.0)
        candidate["real_compiler_log"] = evaluation_result.get("log", "")
        
        print(f"[DGM OUTER LOOP] Kết quả Real Compiler: Đạt {candidate['fitness_score'] * 100:.2f}% Pass Rate")

        # 5. Post-mortem Analysis: Nếu code lỗi, Diagnoser phân tích log để Inner Loop rút kinh nghiệm
        if candidate["fitness_score"] < 1.0:
            candidate["diagnosis_feedback"] = self.diagnoser.diagnose(candidate["code"], candidate["real_compiler_log"])

        # Lưu lại 'ADN' của thế hệ này vào archive
        candidate["hyperparams"] = HYPERPARAMS.to_dict()
        self._save_archive(archive_data)

        # 6. Tiến hóa Bậc 2 (Meta-Evolution): Nâng cấp chiến lược chọn cha mẹ mỗi 5 thế hệ
        if self.generation % 5 == 0:
            self._meta_evolve_strategy()

    def _meta_evolve_strategy(self):
        """
        [Khóa luận - C3] Meta-Evolution: LLM tự viết lại thuật toán chọn lọc tự nhiên của chính nó.
        Có đi qua 2 lớp bảo vệ AST Check và Runtime Sandbox để chống Objective Hacking.
        """
        print("\n[META-EVOLUTION] Đang tự động nâng cấp Thuật toán Chọn lọc (evolution_strategy.py)...")
        strategy_path = "dgm_agent_v2/evolution/evolution_strategy.py"
        
        if not os.path.exists(strategy_path):
            return

        with open(strategy_path, "r", encoding='utf-8') as f:
            current_strategy = f.read()

        # Yêu cầu LLM viết lại chiến lược (VD: chuyển từ UCB1 sang Thompson Sampling)
        system_prompt = "You are a meta-learning core. Improve this evolutionary parent selection strategy. Output ONLY the improved python code wrapped in ```python."
        new_strategy_resp = self.llm_client.generate(prompt=current_strategy, system_prompt=system_prompt, temperature=0.9)
        
        # Bóc tách Code
        match = re.search(r"```python\s*(.*?)\s*```", new_strategy_resp, re.DOTALL | re.IGNORECASE)
        new_strategy_code = match.group(1).strip() if match else new_strategy_resp.strip()

        # [LỚP BẢO VỆ KÉP L2a & L2b]
        is_valid, error_msg = StrategyValidator.validate_strategy(new_strategy_code)
        
        if is_valid:
            print("[META-EVOLUTION] Thành công! Chiến lược mới hợp lệ và an toàn.")
            with open(strategy_path, "w", encoding='utf-8') as f:
                f.write(new_strategy_code)
        else:
            print(f"[META-EVOLUTION] Bị từ chối bởi Sandbox Bảo mật: {error_msg}")
